<?php


return [
  'makes' => [
      "ABARTH",
      "AC",
      "AIXAM",
      "ALFA ROMEO",
      "ALPINE",
      "ARIEL",
      "ASTON MARTIN",
      "AUDI",
      "AUSTIN",
      "BAC",
      "BEAUFORD",
      "BENTLEY",
      "BMW",
      "BRISTOL",
      "BUGATTI",
      "BUICK",
      "CADILLAC",
      "CATERHAM",
      "CHESIL",
      "CHEVROLET",
      "CHRYSLER",
      "CITROEN",
      "CORVETTE",
      "CUPRA",
      "CUSTOM VEHICLE",
      "DACIA",
      "DAEWOO",
      "DAIHATSU",
      "DAIMLER",
      "DATSUN",
      "DAX",
      "DODGE",
      "DS AUTOMOBILES",
      "FERRARI",
      "FIAT",
      "FORD",
      "GMC",
      "GREAT WALL",
      "HOLDEN",
      "HONDA",
      "HUMBER",
      "HUMMER",
      "HYUNDAI",
      "INFINITI",
      "ISUZU",
      "JAGUAR",
      "JEEP",
      "JENSEN",
      "KIA",
      "KOENIGSEGG",
      "KTM",
      "LAMBORGHINI",
      "LANCIA",
      "LAND ROVER",
      "LEVC",
      "LEXUS",
      "LEYLAND",
      "LINCOLN",
      "LONDON TAXIS INTERNATIONAL",
      "LOTUS",
      "MASERATI",
      "MAYBACH",
      "MAZDA",
      "MCLAREN",
      "MERCEDES-BENZ",
      "MG",
      "MICROCAR",
      "MINI",
      "MITSUBISHI",
      "MORGAN",
      "MORRIS",
      "NISSAN",
      "NOBLE",
      "OPEL",
      "PERODUA",
      "PEUGEOT",
      "PILGRIM",
      "PLYMOUTH",
      "PONTIAC",
      "PORSCHE",
      "PROTON",
      "RADICAL",
      "RAW",
      "RELIANT",
      "RENAULT",
      "REPLICA",
      "REVA",
      "RILEY",
      "ROLLS-ROYCE",
      "ROVER",
      "SAAB",
      "SEAT",
      "SINGER",
      "SKODA",
      "SMART",
      "SSANGYONG",
      "STANDARD",
      "SUBARU",
      "SUNBEAM",
      "SUZUKI",
      "TESLA",
      "TOYOTA",
      "TRIUMPH",
      "TVR",
      "ULTIMA",
      "VAUXHALL",
      "VOLKSWAGEN",
      "VOLVO",
      "WESTFIELD",
      "WOLSELEY",
      "YAMAHA",
      "ZENOS"
  ],
  'years' => [
    "1990",
    "1991",
    "1992",
    "1993",
    "1994",
    "1995",
    "1996",
    "1997",
    "1998",
    "1999",
    "2000",
    "2001" => ["51"],
    "2002" => ["02", "52"],
    "2003" => ["03", "53"],
    "2004" => ["04", "54"],
    "2005" => ["05", "55"],
    "2006" => ["06", "56"],
    "2007" => ["07", "57"],
    "2008" => ["08", "58"],
    "2009" => ["09", "59"],
    "2010" => ["10", "60"],
    "2011" => ["11", "61"],
    "2012" => ["12", "62"],
    "2013" => ["13", "63"],
    "2014" => ["14", "64"],
    "2015" => ["15", "65"],
    "2016" => ["16", "66"],
    "2017" => ["17", "67"],
    "2018" => ["18", "68"],
    "2019" => ["19", "69"],
    "2020" => ["20", "70"],
  ],
  'colours' => [
    'Beige'       => 'Beige',
    'Black'       => 'Black',
    'Blue'        => 'Blue',
    'Bronze'      => 'Bronze',
    'Brown'       => 'Brown',
    'Burgundy'    => 'Burgundy',
    'Gold'        => 'Gold',
    'Green'       => 'Green',
    'Grey'        => 'Grey',
    'Indigo'      => 'Indigo',
    'Magenta'     => 'Magenta',
    'Maroon'      => 'Maroon',
    'Multicolour' => 'Multicolour',
    'Navy'        => 'Navy',
    'Orange'      => 'Orange',
    'Pink'        => 'Pink',
    'Purple'      => 'Purple',
    'Red'         => 'Red',
    'Silver'      => 'Silver',
    'Turquoise'   => 'Turquoise',
    'White'       => 'White',
    'Yellow'      => 'Yellow'
  ],
  'transmission_types' => [
    "Manual",
    "Automatic",
    "Semi-automatic"
  ],
  'body_types' => [
    "Combi Van",
    "Convertible",
    "Coupé",
    "Estate",
    "Hatchback",
    "MPV",
    "Minibus",
    "Other",
    "Panel Van",
    "Pickup",
    "SUV",
    "Saloon",
    "Sedan",
    "Crossover",
    "Roadsters"
  ] ,
  'fuel_types' => [
    "Petrol",
    "Diesel",
    "LPG",
    "Bio Fuel",
    "Electric",
    "Hybrid - Diesel/Electric",
    "Hybrid - Diesel/Electric Plug-in",
    "Hybrid - Petrol/Electric",
    "Hybrid - Diesel/Plug-in"
  ],
  'tax_bands' => [
    "£0",
    "Up to £20",
    "Up to £30",
    "Up to £110",
    "Up to £130",
    "Up to £145",
    "Up to £",
    "Up to £",
    "Up to £",
    "Up to £",
    "Up to £",
    "Up to £",
    "Up to £",
    "Up to £",
  ],

  'supported_image_mimes' => [
    "image/jpeg",
    "image/jpg",
    "image/png",
    "image/gif",
    "image/webp"
  ],
  'supported_video_mimes' => [
    "video/mp4"
  ],
  'supported_panorama_image_mimes' => [
    "image/jpeg",
    "image/jpg",
    "image/png"
  ],
  'media_collection_limit' => [
    'tiny'   => 3,
    'small'  => 6,
    'medium' => 12,
    'large'  => 24
  ],

];




















