<?php


return [

  'lists' => [
    'makes' => [
      "Abarth",
      "AC",
      "Aixam",
      "Alfa Romeo",
      "Alpine",
      "Ariel",
      "Aston Martin",
      "Audi",
      "Austin",
      "BAC",
      "Beauford",
      "Bentley",
      "BMW",
      "Bristol",
      "Bugatti",
      "Buick",
      "Cadillac",
      "Caterham",
      "Chesil",
      "Chevrolet",
      "Chrysler",
      "Citroen",
      "Corvette",
      "Cupra",
      "Custom Vehicle",
      "Dacia",
      "Daewoo",
      "Daihatsu",
      "Daimler",
      "Datsun",
      "Dax",
      "Dodge",
      "DS Automobiles",
      "Ferrari",
      "Fiat",
      "Ford",
      "GMC",
      "Great Wall",
      "Holden",
      "Honda",
      "Humber",
      "Hummer",
      "Hyundai",
      "Infiniti",
      "Isuzu",
      "Jaguar",
      "Jeep",
      "Jensen",
      "Kia",
      "Koenigsegg",
      "KTM",
      "Lamborghini",
      "Lancia",
      "Land Rover",
      "Levc",
      "Lexus",
      "Leyland",
      "Lincoln",
      "London Taxis International",
      "Lotus",
      "Maserati",
      "Maybach",
      "Mazda",
      "Mclaren",
      "Mercedes-Benz",
      "MG",
      "Microcar",
      "Mini",
      "Mitsubishi",
      "Morgan",
      "Morris",
      "Nissan",
      "Noble",
      "Opel",
      "Perodua",
      "Peugeot",
      "Pilgrim",
      "Plymouth",
      "Pontiac",
      "Porsche",
      "Proton",
      "Radical",
      "Raw",
      "Reliant",
      "Renault",
      "Replica",
      "Reva",
      "Riley",
      "Rolls-Royce",
      "Rover",
      "Saab",
      "SEAT",
      "Singer",
      "Skoda",
      "Smart",
      "Ssangyong",
      "Standard",
      "Subaru",
      "Sunbeam",
      "Suzuki",
      "Tesla",
      "Toyota",
      "Triumph",
      "TVR",
      "Ultima",
      "Vauxhall",
      "Volkswagen",
      "Volvo",
      "Westfield",
      "Wolseley",
      "Yamaha",
      "Zenos"
    ],
    'body_types' => [
      "Combi Van",
      "Convertible",
      "Coupé",
      "Estate",
      "Hatchback",
      "MPV",
      "Minibus",
      "Other",
      "Panel Van",
      "Pickup",
      "SUV",
      "Saloon",
      "Sedan",
      "Crossover",
      "Roadsters"
    ],
    'transmission_types' => [
      "Manual",
      "Automatic",
      "Semi-automatic"
    ],
    'fuel_types' => [
      "Petrol",
      "Diesel",
      "LPG",
      "Bio Fuel",
      "Electric",
      "Hybrid - Diesel/Electric",
      "Hybrid - Diesel/Electric Plug-in",
      "Hybrid - Petrol/Electric",
      "Hybrid - Diesel/Plug-in"
    ],
    'colours' => [
      'Beige',
      'Black',
      'Blue',
      'Bronze',
      'Brown',
      'Burgundy',
      'Gold',
      'Green',
      'Grey',
      'Indigo',
      'Magenta',
      'Maroon',
      'Multicolour',
      'Navy',
      'Orange',
      'Pink',
      'Purple',
      'Red',
      'Turquoise',
      'White',
      'Yellow'
    ],
    'limits' => [
      15,
      30,
      60,
      120,
    ],
    'order_bys' => [
      [ "text" => "Most recent", "value" => "-date" ],
      [ "text" => "Price (Lowest)", "value" => "price" ],
      [ "text" => "Price (Highest)", "value" => "-price" ],
      [ "text" => "Age (Newest first)", "value" => "-year" ],
      [ "text" => "Mileage", "value" => "miles" ],
    ],
  ],


  'years' => [
    "1990",
    "1991",
    "1992",
    "1993",
    "1994",
    "1995",
    "1996",
    "1997",
    "1998",
    "1999",
    "2000",
    "2001" => ["51"],
    "2002" => ["02", "52"],
    "2003" => ["03", "53"],
    "2004" => ["04", "54"],
    "2005" => ["05", "55"],
    "2006" => ["06", "56"],
    "2007" => ["07", "57"],
    "2008" => ["08", "58"],
    "2009" => ["09", "59"],
    "2010" => ["10", "60"],
    "2011" => ["11", "61"],
    "2012" => ["12", "62"],
    "2013" => ["13", "63"],
    "2014" => ["14", "64"],
    "2015" => ["15", "65"],
    "2016" => ["16", "66"],
    "2017" => ["17", "67"],
    "2018" => ["18", "68"],
    "2019" => ["19", "69"],
    "2020" => ["20", "70"],
  ],
  'tax_bands' => [
    "£0",
    "Up to £20",
    "Up to £30",
    "Up to £110",
    "Up to £130",
    "Up to £145",
    "Up to £",
    "Up to £",
    "Up to £",
    "Up to £",
    "Up to £",
    "Up to £",
    "Up to £",
    "Up to £",
  ],

  'popular_makes_limit' => 10,

  'cache' => [
    'remember_ttl' => 10080
  ],

  'supported_image_mimes' => [
    "image/jpeg",
    "image/jpg",
    "image/png",
    "image/gif",
    "image/webp"
  ],
  'supported_video_mimes' => [
    "video/mp4"
  ],
  'supported_panorama_image_mimes' => [
    "image/jpeg",
    "image/jpg",
    "image/png"
  ],
  'media_collection_limit' => [
    'tiny'   => 3,
    'small'  => 6,
    'medium' => 12,
    'large'  => 24
  ],
];




















